### ISSUE TITLE
any plan to upgrade the conda environment?

### ISSUE THREAD

**Issue by jingpengw** [janelia-flyem/neuclease#15]
My packages used some new features of Python 3.9. It does not work with Python 3.7 anymore.
I am wondering is there any plan to upgrade the conda environment?

I tried to compile dvidutils myself, but got an error of draco.
```
/mnt/home/jwu/anaconda3/envs/cf/include/draco/attributes/point_attribute.h:46:8: note: candidate: ‘void draco::PointAttribute::Init(draco::GeometryAttribute::Type, int8_t, draco::DataType,[74/649]
td::size_t)’
   void Init(Type attribute_type, int8_t num_components, DataType data_type,
        ^~~~
/mnt/home/jwu/anaconda3/envs/cf/include/draco/attributes/point_attribute.h:46:8: note:   candidate expects 5 arguments, 7 provided
In file included from /mnt/home/jwu/code/dvidutils/src/main.cpp:22:
/mnt/home/jwu/code/dvidutils/src/pydraco.hpp:118:39: error: no matching function for call to ‘draco::PointAttribute::Init(draco::GeometryAttribute::Type, std::nullptr_t, int, draco::DataType, bool
, int32_t, int)’
                                     0 );                            // byte_offset
                                       ^
In file included from /mnt/home/jwu/anaconda3/envs/cf/include/draco/point_cloud/point_cloud.h:18,
                 from /mnt/home/jwu/anaconda3/envs/cf/include/draco/mesh/mesh.h:29,
                 from /mnt/home/jwu/code/dvidutils/src/pydraco.hpp:8,
                 from /mnt/home/jwu/code/dvidutils/src/main.cpp:22:
/mnt/home/jwu/anaconda3/envs/cf/include/draco/attributes/point_attribute.h:46:8: note: candidate: ‘void draco::PointAttribute::Init(draco::GeometryAttribute::Type, int8_t, draco::DataType, bool, s
td::size_t)’
   void Init(Type attribute_type, int8_t num_components, DataType data_type,
        ^~~~
/mnt/home/jwu/anaconda3/envs/cf/include/draco/attributes/point_attribute.h:46:8: note:   candidate expects 5 arguments, 7 provided
make[2]: *** [CMakeFiles/_dvidutils.dir/build.make:90: CMakeFiles/_dvidutils.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:87: CMakeFiles/_dvidutils.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

**Comment by stuarteberg** [comment]
Yes, the latest version of neuclease and dvidutils use python 3.10.  Try creating a conda environment with python 3.10

```
mamba create -n myenv -c flyem-forge -c conda-forge python=3.10 'neuclease>=0.5.post105'
```

**Comment by jingpengw** [comment]
great! it works for me!
I did not use both channels together previously.
